stages:
- name: deploy
  steps:
  - applyYamlConfig:
      path: ./deployment.yaml
    env:
      NIFI_WEB_HTTP_PORT: "7070"
  - applyYamlConfig:
      path: ./service.yaml
timeout: 60
notification: {}
