apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: draco2
spec:
  replicas: 2
  template:
   metadata:
     labels:
       name: draco2
   spec:
     containers:
     - name: draco2
       image: csp2-centos-1:5000/nifi_test_bare_2
       ports:
       - containerPort: 7070
       - containerPort: 7575
       - containerPort: 7979
