apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: draco2-ingress
  annotations:
    ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: new.draco.com
    http:
      paths:
      - path: /
        backend:
          serviceName: draco2-service
          servicePort: 7070
