apiVersion: v1
kind: Service
metadata:
  name: new-draco-service
  labels:
    name: new-draco
spec:
  type: NodePort
  ports:
    - port: 7474
      nodePort: 30016
      name: http
  selector:
    name: new-draco
