apiVersion: v1
kind: Service
metadata:
  name: draco2-service
  labels:
    name: draco2-service
spec:
  type: NodePort
  ports:
    - port: 7474
      nodePort: 30016
      name: http
  selector:
    name: draco2
